from __future__ import annotations

from .models import Movie


SEED_MOVIES = [
    Movie(
        id="parasite",
        title="Parasite",
        type="Movie",
        release_year=2019,
        genres=["Thriller", "Dark Comedy", "Drama"],
        tags=["class tension", "dark comedy", "revenge", "rich people drama", "tense"],
        description="A poor family infiltrates a wealthy household, setting off a sharp, funny, and brutal class thriller.",
        cast=["Song Kang-ho", "Cho Yeo-jeong", "Park So-dam"],
        director="Bong Joon Ho",
        country=["South Korea"],
        availability_region=["US", "CA", "UK"],
        rating="R",
        duration="132 min",
        platform="Demo catalog",
    ),
    Movie(
        id="arrival",
        title="Arrival",
        type="Movie",
        release_year=2016,
        genres=["Sci-Fi", "Drama"],
        tags=["emotional sci-fi", "loneliness", "language", "grief", "thoughtful"],
        description="A linguist helps decode alien communication while confronting time, memory, and grief.",
        cast=["Amy Adams", "Jeremy Renner", "Forest Whitaker"],
        director="Denis Villeneuve",
        country=["US", "Canada"],
        availability_region=["US", "CA"],
        rating="PG-13",
        duration="116 min",
        platform="Demo catalog",
    ),
    Movie(
        id="the-menu",
        title="The Menu",
        type="Movie",
        release_year=2022,
        genres=["Thriller", "Dark Comedy"],
        tags=["rich people drama", "revenge", "dark funny", "tense", "satire"],
        description="A luxury dinner becomes a venomous satire of wealth, taste, obsession, and revenge.",
        cast=["Ralph Fiennes", "Anya Taylor-Joy", "Nicholas Hoult"],
        director="Mark Mylod",
        country=["US"],
        availability_region=["US", "CA"],
        rating="R",
        duration="107 min",
        platform="Demo catalog",
    ),
    Movie(
        id="paddington-2",
        title="Paddington 2",
        type="Movie",
        release_year=2017,
        genres=["Family", "Comedy", "Adventure"],
        tags=["comfort", "rainy night", "warm", "gentle", "family friendly"],
        description="A kind bear brings warmth, slapstick, and unexpected grace to a charming neighborhood caper.",
        cast=["Ben Whishaw", "Hugh Grant", "Sally Hawkins"],
        director="Paul King",
        country=["UK"],
        availability_region=["US", "UK", "CA"],
        rating="PG",
        duration="103 min",
        platform="Demo catalog",
    ),
    Movie(
        id="eternal-sunshine",
        title="Eternal Sunshine of the Spotless Mind",
        type="Movie",
        release_year=2004,
        genres=["Romance", "Sci-Fi", "Drama"],
        tags=["breakup", "emotional", "memory", "melancholy", "mind-bending"],
        description="After a breakup, two people erase each other from memory and rediscover what made the relationship matter.",
        cast=["Jim Carrey", "Kate Winslet", "Kirsten Dunst"],
        director="Michel Gondry",
        country=["US"],
        availability_region=["US", "UK"],
        rating="R",
        duration="108 min",
        platform="Demo catalog",
    ),
    Movie(
        id="knives-out",
        title="Knives Out",
        type="Movie",
        release_year=2019,
        genres=["Mystery", "Comedy", "Crime"],
        tags=["smart dialogue", "rich family", "funny", "murder mystery", "witty"],
        description="A detective investigates a rich family's tangled motives after a famous novelist dies.",
        cast=["Daniel Craig", "Ana de Armas", "Chris Evans"],
        director="Rian Johnson",
        country=["US"],
        availability_region=["US", "AU"],
        rating="PG-13",
        duration="130 min",
        platform="Demo catalog",
    ),
    Movie(
        id="the-nice-guys",
        title="The Nice Guys",
        type="Movie",
        release_year=2016,
        genres=["Comedy", "Crime", "Action"],
        tags=["chaotic friends", "buddy comedy", "crime", "smart dialogue", "funny"],
        description="A bruiser and a private eye stumble through a grimy, hilarious Los Angeles conspiracy.",
        cast=["Ryan Gosling", "Russell Crowe", "Angourie Rice"],
        director="Shane Black",
        country=["US"],
        availability_region=["US"],
        rating="R",
        duration="116 min",
        platform="Demo catalog",
    ),
    Movie(
        id="ex-machina",
        title="Ex Machina",
        type="Movie",
        release_year=2014,
        genres=["Sci-Fi", "Thriller"],
        tags=["mind-bending", "AI", "tense", "isolation", "not marvel"],
        description="A programmer evaluates a humanoid AI in a sleek remote compound where every conversation is a trap.",
        cast=["Alicia Vikander", "Domhnall Gleeson", "Oscar Isaac"],
        director="Alex Garland",
        country=["UK"],
        availability_region=["US", "UK"],
        rating="R",
        duration="108 min",
        platform="Demo catalog",
    ),
    Movie(
        id="her",
        title="Her",
        type="Movie",
        release_year=2013,
        genres=["Romance", "Sci-Fi", "Drama"],
        tags=["loneliness", "emotional sci-fi", "soft", "melancholy", "love"],
        description="A lonely writer falls for an operating system in a tender near-future story about intimacy.",
        cast=["Joaquin Phoenix", "Scarlett Johansson", "Amy Adams"],
        director="Spike Jonze",
        country=["US"],
        availability_region=["US", "UK"],
        rating="R",
        duration="126 min",
        platform="Demo catalog",
    ),
    Movie(
        id="the-bear",
        title="The Bear",
        type="Show",
        release_year=2022,
        genres=["Drama", "Comedy"],
        tags=["kitchen", "stressful", "found family", "prestige", "chaotic"],
        description="A gifted chef returns home to run a sandwich shop, turning grief and pressure into combustible drama.",
        cast=["Jeremy Allen White", "Ayo Edebiri", "Ebon Moss-Bachrach"],
        director="Christopher Storer",
        country=["US"],
        availability_region=["US"],
        rating="TV-MA",
        duration="3 seasons",
        platform="Demo catalog",
    ),
    Movie(
        id="chef",
        title="Chef",
        type="Movie",
        release_year=2014,
        genres=["Comedy", "Drama"],
        tags=["less stressful", "food", "comfort", "warm", "family"],
        description="A burned-out chef starts over with a food truck, his son, and a renewed love of making things.",
        cast=["Jon Favreau", "Sofia Vergara", "John Leguizamo"],
        director="Jon Favreau",
        country=["US"],
        availability_region=["US", "CA"],
        rating="R",
        duration="114 min",
        platform="Demo catalog",
    ),
    Movie(
        id="zodiac",
        title="Zodiac",
        type="Movie",
        release_year=2007,
        genres=["Crime", "Thriller", "Drama"],
        tags=["slow-burn", "crime", "obsession", "smart", "intense not horror"],
        description="Journalists and detectives become consumed by the hunt for a serial killer in a patient procedural.",
        cast=["Jake Gyllenhaal", "Mark Ruffalo", "Robert Downey Jr."],
        director="David Fincher",
        country=["US"],
        availability_region=["US"],
        rating="R",
        duration="157 min",
        platform="Demo catalog",
    ),
]
